# Generated by Django 3.2.6 on 2021-08-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0006_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('active', 'Active'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='created', max_length=255),
        ),
    ]
