# Generated by Django 3.2.6 on 2021-08-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0008_job_job_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_definition',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
