# Generated by Django 3.2.6 on 2021-08-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0014_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('active', 'Active'), ('killed', 'Killed'), ('completed', 'Completed')], default='created', max_length=255),
        ),
    ]
