# Generated by Django 3.2.6 on 2021-08-06 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0015_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='worlds.job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('active', 'Active'), ('killed', 'Killed'), ('failed', 'Failed'), ('completed', 'Completed')], default='created', max_length=25),
        ),
    ]
