# Generated by Django 3.2.5 on 2021-07-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('slug', models.SlugField(max_length=70, unique=True)),
                ('worker_command', models.CharField(max_length=512)),
                ('workers', models.PositiveSmallIntegerField()),
                ('envs', models.TextField(help_text='use .env format')),
            ],
        ),
    ]
