# Generated by Django 3.2.5 on 2021-07-26 16:59

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0002_alter_pipeline_envs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='envs',
            field=fernet_fields.fields.EncryptedTextField(blank=True, help_text='use .env format', null=True),
        ),
    ]
