# Generated by Django 3.2.6 on 2021-08-02 15:24

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0003_alter_pipeline_envs'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='config',
            field=fernet_fields.fields.EncryptedTextField(blank=True, help_text='kube config file', null=True),
        ),
    ]
