# Generated by Django 3.2.6 on 2021-08-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0007_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
