# Generated by Django 3.2.6 on 2021-08-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0010_alter_job_job_definition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('active', 'Active'), ('completed', 'Completed')], default='created', max_length=255),
        ),
    ]
