# Generated by Django 3.2.6 on 2021-08-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0012_auto_20210804_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='logs',
        ),
        migrations.AddField(
            model_name='job',
            name='log_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
