# Generated by Django 3.2.6 on 2021-08-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0018_pipeline_force_scaling'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='scale_down_delay',
            field=models.PositiveSmallIntegerField(default=1200),
        ),
    ]
