# Generated by Django 3.2.6 on 2021-08-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0019_pipeline_scale_down_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='port',
            field=models.PositiveSmallIntegerField(default=17777),
            preserve_default=False,
        ),
    ]
