# Generated by Django 3.2.6 on 2021-08-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0021_alter_job_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='master_node_selector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='worker_node_selector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
