# Generated by Django 3.2.6 on 2021-08-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0022_auto_20210819_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='job_storage_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
