# Generated by Django 3.2.6 on 2021-08-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0023_pipeline_job_storage_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeline',
            name='job_storage_url',
        ),
        migrations.AddField(
            model_name='pipeline',
            name='s3_storage',
            field=models.BooleanField(default=False),
        ),
    ]
