# Generated by Django 3.2.6 on 2021-08-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0024_auto_20210823_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeline',
            name='s3_storage',
        ),
        migrations.AddField(
            model_name='pipeline',
            name='s3_storage_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
