# Generated by Django 3.2.6 on 2021-08-23 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0025_auto_20210823_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pod', models.CharField(max_length=255)),
                ('logs', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds.job')),
            ],
            options={
                'ordering': ['-modified'],
                'unique_together': {('job', 'pod')},
            },
        ),
    ]
