# Generated by Django 3.2.6 on 2021-08-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0026_streamlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamlog',
            name='lines',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
