# Generated by Django 3.2.6 on 2021-08-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0027_streamlog_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamlog',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('completed', 'Completed')], default='created', max_length=25),
        ),
    ]
