# Generated by Django 3.2.6 on 2021-08-23 18:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0028_streamlog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='pod_watchers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
