# Generated by Django 3.2.6 on 2021-08-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0029_job_pod_watchers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('downloading', 'Downloading Container'), ('active', 'Active'), ('killed', 'Killed'), ('failed', 'Failed'), ('completed', 'Completed')], default='created', max_length=25),
        ),
    ]
