# Generated by Django 3.2.6 on 2021-08-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0030_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamlog',
            name='retries',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
