# Generated by Django 3.2.6 on 2021-08-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0032_alter_streamlog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='post_command',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='pre_command',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
