# Generated by Django 3.2.6 on 2021-08-26 19:57

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0033_auto_20210826_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='envs',
            field=fernet_fields.fields.EncryptedTextField(blank=True, help_text='use .env format', null=True),
        ),
    ]
