# Generated by Django 3.2.6 on 2021-09-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0034_job_envs'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamlog',
            name='log_file',
            field=models.FileField(blank=True, null=True, upload_to='warpzone/%Y/%m/%d/'),
        ),
    ]
