# Generated by Django 3.2.6 on 2021-09-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0035_streamlog_log_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamlog',
            name='logs',
        ),
    ]
