# Generated by Django 3.2.10 on 2021-12-10 17:23

from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0040_auto_20211203_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('slug', models.SlugField(max_length=70, unique=True)),
                ('external_id', models.CharField(max_length=255)),
                ('config', fernet_fields.fields.EncryptedTextField(blank=True, help_text='kube config file', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NodePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('external_id', models.CharField(max_length=255)),
                ('scale_up_desired_size', models.PositiveSmallIntegerField(default=5)),
                ('scale_up_min_size', models.PositiveSmallIntegerField(default=5)),
                ('scale_up_max_size', models.PositiveSmallIntegerField(default=5)),
                ('scale_down_desired_size', models.PositiveSmallIntegerField(default=2)),
                ('scale_down_min_size', models.PositiveSmallIntegerField(default=2)),
                ('scale_down_max_size', models.PositiveSmallIntegerField(default=2)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds.cluster')),
            ],
        ),
    ]
