# Generated by Django 3.2.10 on 2021-12-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0043_cluster_scale_down_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodepool',
            name='current_size',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
