# Generated by Django 3.2.10 on 2021-12-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0045_pipeline_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
