# Generated by Django 3.2.10 on 2021-12-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0046_cluster_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='queue',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='master_node_selector',
        ),
    ]
