# Generated by Django 3.2.10 on 2021-12-14 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0047_auto_20211213_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipeline',
            old_name='config',
            new_name='config_old',
        ),
    ]
