# Generated by Django 3.2.10 on 2022-01-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0049_job_shelix_log_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedlog',
            name='pod',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
