# Generated by Django 3.2.10 on 2022-01-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0050_alter_completedlog_pod'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='logging',
            field=models.CharField(choices=[('kube', 'Kubernetes'), ('shelix', 'Star Helix')], default='kube', max_length=10),
        ),
    ]
