# Generated by Django 3.2.10 on 2022-01-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0051_pipeline_logging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='scale_down_delay',
            field=models.PositiveIntegerField(default=1200),
        ),
    ]
