# Generated by Django 3.2.10 on 2022-01-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0052_alter_cluster_scale_down_delay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeline',
            name='scale_down_delay',
        ),
    ]
