# Generated by Django 3.2.10 on 2022-04-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0054_job_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='port',
        ),
        migrations.AddField(
            model_name='pipeline',
            name='port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
