# Generated by Django 3.2.10 on 2022-05-19 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0055_auto_20220415_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('cpu', models.CharField(max_length=25)),
                ('memory', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='scale_down_delay',
        ),
        migrations.DeleteModel(
            name='NodePool',
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='worlds.jobtype'),
        ),
    ]
