# Generated by Django 3.2.10 on 2022-05-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0056_auto_20220519_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtype',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='jobtype',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='memory_request',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='port',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='worker_node_selector',
        ),
        migrations.AddField(
            model_name='jobtype',
            name='cpu_limit',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='jobtype',
            name='cpu_request',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='jobtype',
            name='memory_limit',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='jobtype',
            name='memory_request',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='jobtype',
            name='worker_node_selector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
