# Generated by Django 3.2.10 on 2022-05-24 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0057_auto_20220519_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeline',
            name='config_old',
        ),
    ]
